/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib.grupp.pkg15;

import oru.inf.InfDB;

/**
 *
 * @author erike
 */
//Fälten för klassen AdminStartskärm.
public class AdminStartSkärm extends javax.swing.JFrame {

    private String användarnamn;

//    Konstruktorn för AdminStartskärm.
    public AdminStartSkärm(String användarnamn) {
        initComponents();
        this.användarnamn = användarnamn;
        lblRubrik.setText("Välkommen " + användarnamn + " (Administratör).");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        btnMinSida = new javax.swing.JButton();
        btnAgentInfo = new javax.swing.JButton();
        btnAlienInfo = new javax.swing.JButton();
        btnAdminUtrustning = new javax.swing.JButton();
        lblLoggaut = new javax.swing.JButton();
        lblAvsluta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblRubrik.setText("Inloggad som");

        btnMinSida.setText("Min Sida");
        btnMinSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinSidaActionPerformed(evt);
            }
        });

        btnAgentInfo.setText("Hantera Agenter");
        btnAgentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgentInfoActionPerformed(evt);
            }
        });

        btnAlienInfo.setText("Hantera Aliens");
        btnAlienInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlienInfoActionPerformed(evt);
            }
        });

        btnAdminUtrustning.setText("Utrustning");
        btnAdminUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminUtrustningActionPerformed(evt);
            }
        });

        lblLoggaut.setText("Logga ut");
        lblLoggaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLoggautActionPerformed(evt);
            }
        });

        lblAvsluta.setText("Avsluta program");
        lblAvsluta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblAvslutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAlienInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMinSida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdminUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLoggaut))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAvsluta))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblRubrik))
                    .addComponent(lblLoggaut))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlienInfo)
                    .addComponent(btnAgentInfo))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinSida)
                    .addComponent(btnAdminUtrustning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(lblAvsluta))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Knappen öppnar ett nytt fönster med klassen MinSida.
    private void btnMinSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinSidaActionPerformed
        Navigera.openAdminMinSida(användarnamn);
        dispose();
    }//GEN-LAST:event_btnMinSidaActionPerformed
// Knappen för att starta metoden Avsluta program.
    private void lblAvslutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAvslutaActionPerformed
        Navigera.avslutaProgram();
    }//GEN-LAST:event_lblAvslutaActionPerformed
// Knappen för att starta metoden Logga ut.
    private void lblLoggautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLoggautActionPerformed
        Navigera.openStartSkärm();
        dispose();
    }//GEN-LAST:event_lblLoggautActionPerformed
// Knappen öppnar ett nytt fönster med klassen Alien Info.
    private void btnAlienInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlienInfoActionPerformed
        new AdminHanteraAlien(användarnamn).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAlienInfoActionPerformed
//Knappen öppnar ett nytt fönster med klassen Agent Info.
    private void btnAgentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgentInfoActionPerformed
        new AdminHanteraAgent(användarnamn).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgentInfoActionPerformed
//Knappen öppnar ett nytt fönster med klassen Utrustning.
    private void btnAdminUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUtrustningActionPerformed
        new AdminUtrustning(användarnamn).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAdminUtrustningActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminUtrustning;
    private javax.swing.JButton btnAgentInfo;
    private javax.swing.JButton btnAlienInfo;
    private javax.swing.JButton btnMinSida;
    private javax.swing.JButton lblAvsluta;
    private javax.swing.JButton lblLoggaut;
    private javax.swing.JLabel lblRubrik;
    // End of variables declaration//GEN-END:variables
}
