/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib.grupp.pkg15;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Linda
 */
// Fälten för Startskärm.
public class StartSkärm extends javax.swing.JFrame {

    private static InfDB idb;
    private MetoderAgentAdmin AgentM;
    private MetoderAlien AlienM;
    private MetoderUnikaAdmin AdminM;

    /**
     * Konstruktorn för Startskärm
     */
    public StartSkärm() {
        initComponents();
        idb = Main.getDB();
        AgentM = new MetoderAgentAdmin(this);
        AlienM = new MetoderAlien(this);
        AdminM = new MetoderUnikaAdmin(this);
//        txtStartAnvändarnamn.setText("Agent O");
//        pwfStartLogin.setText("planka");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoginAgent = new javax.swing.JButton();
        btnLoginAlien = new javax.swing.JButton();
        btnLoginAdmin = new javax.swing.JButton();
        lblStartRubrik = new javax.swing.JLabel();
        pwfStartLogin = new javax.swing.JPasswordField();
        txtStartAnvändarnamn = new javax.swing.JTextField();
        lblStartAnvändarnamn = new javax.swing.JLabel();
        lblStartLösenord = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLoginAgent.setText("Logga in som Agent");
        btnLoginAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAgentActionPerformed(evt);
            }
        });

        btnLoginAlien.setText("Logga in som Alien");
        btnLoginAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAlienActionPerformed(evt);
            }
        });

        btnLoginAdmin.setText("Logga in som Admin");
        btnLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAdminActionPerformed(evt);
            }
        });

        lblStartRubrik.setText("Välkommen till MIBs databassystem.");

        pwfStartLogin.setColumns(5);

        lblStartAnvändarnamn.setText("Användarnamn");

        lblStartLösenord.setText("Lösenord");

        jLabel1.setText("Vänligen ange ditt användarnamn och lösenord och logga in som din användartyp.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStartRubrik)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoginAgent)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoginAlien)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoginAdmin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblStartAnvändarnamn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStartAnvändarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStartLösenord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pwfStartLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStartRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartAnvändarnamn)
                    .addComponent(txtStartAnvändarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStartLösenord)
                    .addComponent(pwfStartLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoginAgent)
                    .addComponent(btnLoginAlien)
                    .addComponent(btnLoginAdmin))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Knappen som startar metoden för att logga in som Admin.
    private void btnLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAdminActionPerformed
        MetoderUnikaAdmin.loggainAdmin(txtStartAnvändarnamn, pwfStartLogin);
    }//GEN-LAST:event_btnLoginAdminActionPerformed
// Knappen som startar metoden för att logga in som Alien.
    private void btnLoginAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAlienActionPerformed
        MetoderAlien.loggaInAlien(txtStartAnvändarnamn, pwfStartLogin);
    }//GEN-LAST:event_btnLoginAlienActionPerformed
// Knappen som startar metoden för att logga in som Agent.
    private void btnLoginAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAgentActionPerformed
        MetoderAgentAdmin.loggainAgent(txtStartAnvändarnamn, pwfStartLogin);

    }//GEN-LAST:event_btnLoginAgentActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginAdmin;
    private javax.swing.JButton btnLoginAgent;
    private javax.swing.JButton btnLoginAlien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStartAnvändarnamn;
    private javax.swing.JLabel lblStartLösenord;
    private javax.swing.JLabel lblStartRubrik;
    private javax.swing.JPasswordField pwfStartLogin;
    private javax.swing.JTextField txtStartAnvändarnamn;
    // End of variables declaration//GEN-END:variables
}
